#!/bin/sh
# Name: $RCSfile$
# CVS file: $Source$
# CVS id: $Header$
# Revision: $Revision$
# Revised on: $Date$
# Revised by: $Author$
# License: This script is licensed as GPL ( http://www.gnu.org/licenses/old-licenses/gpl-2.0.html )
# Support: Fernando Nunes - domusonline@gmail.com



get_setinfx_conf_dir()
{
	INFORMIX_HOME=`grep "^informix:" /etc/passwd | cut -f6 -d':'`
	CONF_DIRS="${INFORMIX_HOME}/etc /usr/bin/utils /usr/bin/scripts"
	for DIR in ${CONF_DIRS}
	do
		if [ -r ${DIR}/${INFX_CONF} ]
		then
			echo ${DIR}
			return 0
		fi
	done
	return 1
}

get_setinfx_conf_file()
{
	IFMX_ETC=`get_setinfx_conf_dir`
	if [ "X${IFMX_ETC}" = "X" ]
	then
		echo
		return 1
	else
		if [ "X${SETINFX_ENV_FILE}" = "X" ]
		then
			ENV_FILE=${IFMX_ETC}/infx_env.lst
		else
			ENV_FILE=${IFMX_ETC}/${SETINFX_ENV_FILE}
		fi
	fi
	if [ "X${ENV_FILE}" = "X" ]
	then
		echo
		return 1
	else
		echo ${ENV_FILE}
		return 0
	fi
}

get_setinfx_admin_list()
{
	ENV_FILE=`get_setinfx_conf_file`
	if [ $? != 0 ]
	then
		echo
		return 1
	fi
	if [ "X${ENV_FILE}" = "X" ]
	then
		echo
		return 1
	else
		HOST=`hostname | cut -f1 -d'.' | tr [:lower:] [:upper:]`
		cat ${ENV_FILE} | grep -v "^$" | grep -v "^#" |  ${SETINFX_UTILS_AWK} -F'|' -v "host=${HOST}" 'BEGIN {linha=1;host="^"host"(\\.|$)"} { if ($1 ~ "^inactiv" ) {linha++;next}; if ( ($7 == "S") && ((toupper($9) ~ host) || (toupper($9) == "LOCAL") )) {printf "%s ",linha};linha++} END {printf "\n"}'
		if [ $? != 0 ]
		then
			return 1
		else
			return 0
		fi
	fi
}

get_setinfx_admin_num_by_server()
{
	IX_SERVER=$1
	if [ "X${IX_SERVER}" = "X" ]
	then
		return 1
	else
		IX_SERVER=`echo ${IX_SERVER} | tr [:lower:] [:upper:]`
	fi
	ENV_FILE=`get_setinfx_conf_file`
	if [ $? != 0 ]
	then
		echo
		return 1
	fi
	if [ "X${ENV_FILE}" = "X" ]
	then
		echo
		return 1
	else
		HOST=`hostname | cut -f1 -d'.' | tr [:lower:] [:upper:]`
		cat ${ENV_FILE} | grep -v "^$" | grep -v "^#" |  ${SETINFX_UTILS_AWK} -F'|' -v "host=${HOST}" -v"IX_SERVER=${IX_SERVER}" 'BEGIN {linha=1;host="^"host"(\\.|$)"} { if ($1 ~ "^inactiv" ) {linha++;next}; if ( ($7 == "S") && ((toupper($9) ~ host) || (toupper($9) == "LOCAL") ) && (toupper($2) == IX_SERVER )) {printf "%s ",linha};linha++} END {printf "\n"}'
	fi

	if [ $? != 0 ]
	then
		return 1
	else
		return 0
	fi
}

get_setinfx_admin_server_by_num()
{
	IX_NUM=$1
	if [ "X${IX_NUM}" = "X" ]
	then
		return 1
	else
		echo $IX_NUM | grep "^[1-9][0-9]*" >/dev/null
		if [ $? != 0 ]
		then
			return 1
		fi
	fi
	ENV_FILE=`get_setinfx_conf_file`
	if [ $? != 0 ]
	then
		echo
		return 1
	fi
	if [ "X${ENV_FILE}" = "X" ]
	then
		echo
		return 1
	else
		HOST=`hostname | cut -f1 -d'.' | tr [:lower:] [:upper:]`
		cat ${ENV_FILE} | grep -v -e "^$" -e "^#" |  ${SETINFX_UTILS_AWK} -F'|' -v "host=${HOST}" -v"IX_NUM=${IX_NUM}" '
BEGIN {
	linha=1;
	host="^"host"(\\.|$)"
	FOUND=0;
}
{
	if ($1 ~ "^inactiv" )
	{
		linha++;next
	}
	if ( linha == IX_NUM )
	{
		print $2;
		FOUND=1;
		exit 0		
	}
	else
	{
		if (linha > IX_NUM)
		{
			exit 1
		}
		else
		{
			linha++
		}
	}
}
END { if (FOUND == 1 ) exit 0; else exit 1}'

	fi

	if [ $? != 0 ]
	then
		return 1
	else
		return 0
	fi
}

SO=`uname -s | tr "[:upper:]" "[:lower:]"`
case $SO in
sunos*)
        SETINFX_UTILS_AWK=nawk
        ;;
osf*)
        SETINFX_UTILS_AWK=nawk
        ;;
linux|*)
        SETINFX_UTILS_AWK=awk
        ;;
esac
