#!/bin/sh
# Copyright (c) 2001-2016 Fernando Nunes - domusonline@gmail.com
# License: This script is licensed as GPL V2 ( http://www.gnu.org/licenses/old-licenses/gpl-2.0.html )
# $Author: Fernando Nunes - domusonline@gmail.com $
# $Revision: 2.0.39 $
# $Date: 2018-04-03 17:28:33 $
# Disclaimer: This software is provided AS IS, without any kind of guarantee. Use at your own risk.
#             Although the author is/was an IBM employee, this software was created outside his job engagements.
#             As such, all credits are due to the author.
# Script to create the 'update statisics' statements as discribed in the Performance Guide
# This script assumes all environment variables are set.

#-------------------------------------------------------
# parameter processing
#-------------------------------------------------------

PROGNAME=`basename $0`
VERSION=`echo "$Revision: 2.0.39 $" | cut -f2 -d' '`

DEFAULT_RESOLUTION_MEDIUM=2.5

# Do not ignore dbaccess errors
DBACCNOIGN=1
export DBACCNOIGN

DELIMIDENT=yes
export DELIMIDENT


show_help()
{
	echo "${PROGNAME}: -h | -V | { [-d] database } { [-t] table } [ -e | -E file ] [ -p priority ]\n [ -m size ] [ -r resolution ] [ -c confidence ] [ -R resolution ] [ -l ] [ -x|X ] [ -T ] [ -F | -S {stat_change}]" 
	echo "               { [ -d ] database } (required)"
	echo "               { [-t] table}  (required)"
	echo "               [-h] Show help and exit"
	echo "               [-V] Show version and exit"
	echo "               [-p] Set PDQPRIORITY (versions >= 7.31.UD2 and 9.30.UC2)"
	echo "               [-r resolution] Set resolution for MEDIUM distributions"
	echo "               [-c confidence] Set confidence"
	echo "               [-R resolution] Set resolution for HIGH distributions"
	echo "               [-m size] Set sampling size (versions >= 11.10)"
	echo "               [-l] Use quick LOW mode (Avoid b-tree leaf scan Only minimal table info is collected)"
	echo "               [-e] Set explain on (versions >= 7.31.UD2 and 9.30.UC2)"
	echo "               [-E file ] Set explain file (versions >= 11.10)"
	echo "               [-X] Display and execute"
	echo "               [-x] Display only. Don't execute"
	echo "               [-T] Include timings in de SQL generated"
	echo "               [-o user] define owner for ANSI databases"
	echo "               [-i] Set DIRTY READ isolation level"
	echo "               [-a] Database is ANSI (includes COMMIT after each UPD. STAT. cmd to avoid locking)"
	echo "               [-w N] Set LOCK MODE TO WAIT N seconds"
	echo "               [-F] to force statistics even if AUTO_STAT_MODE is on"
	echo "               [-S stat_change] to define a STATCHANGE value and work in AUTO mode"
}

get_args()
{
	arg_ok="d:t:p:m:r:R:c:E:hleVTxXo:S:iaw:F"
	while getopts ${arg_ok} OPTION
	do
		case ${OPTION} in
		h)   # show help
			show_help
			exit 0
			;;
		V)   # show version
			echo "${PROGNAME} version ${VERSION}"
			exit 0
			;;
		l)   # quick low mode
			LOW_MODE_FLAG=1
			;;
		T)   # show timings (to stdout)
			TIMINGS_FLAG=1
			;;
		e)   # set up the -e (set explain flag)
			EXPLAIN_FLAG=1
			;;
		E)   # set up the -e (set explain flag)
			EXPLAIN_FLAG=2
			explain_file=${OPTARG}
			;;
		i)   # set up the -i (set DIRTY_READ flag)
			DIRTY_READ_FLAG=1
			;;
		a)   # set up the -a (set ANSI flag)
			ANSI_FLAG=1
			;;
		x)   # set up the -x (set DISPLAY_ONLY flag)
			DISPLAY_FLAG=1
			;;
		X)   # set up the -X (set DISPLAY_&_EXECUTE flag)
			DISPLAY_FLAG=2
			;;
		d)   # set up the -d (database flag)
			DATABASE_FLAG=1
			DATABASE=${OPTARG}
			;;
		t)   # set up the -f (filter flag)
			TABLE_FLAG=1
			tabname=${OPTARG}
			;;
		p)   # set up the -p ( PDQPRIORITY flag)
			PRIORITY_FLAG=1
			priority=${OPTARG}
			;;
		w)   # set up the -w ( LOCK MODE flag)
			LOCK_MODE_FLAG=1
			LOCK_MODE_TIME=${OPTARG}
			echo ${LOCK_MODE_TIME} | grep "^[1-9][0-9]*" >/dev/null
 			if [ $? != 0  ]
			then
				echo "${PROGNAME} Syntax error: LOCK WAIT time must be between a number >= 1" >&2
				return 1
			fi
			;;
		m)   # set up the -m (sampling flag)
			SAMPLING_FLAG=1
			sampling=${OPTARG}
			;;
		R)   # set up the -R (resolution High flag)
			RESOLUTION_HIGH_FLAG=1
			resolution_high=${OPTARG}
			;;
		r)   # set up the -r (resolution medium flag)
			RESOLUTION_MEDIUM_FLAG=1
			resolution_medium=${OPTARG}
			;;
		c)   # set up the -c (confidence flag)
			CONFIDENCE_FLAG=1
			confidence=${OPTARG}
			;;
		o)   # set up the -u (ANSI user flag)
			ANSI_USER_FLAG=1
			ANSI_USER=${OPTARG}
			;;
		F)   # FORCE mode for AUTO_STAT_MODE
			if [ "X${STATCHANGE_FLAG}" != "X" ]
			then
				echo "${PROGNAME} Syntax error: Option -F cannot be used with -S" >&2
				return 1
			else
				FORCE_FLAG=1
			fi
                        ;;
		S)   # set up the -S (SET SESSION flag)
			if [ "X${FORCE_FLAG}" != "X" ]
			then
				echo "${PROGNAME} Syntax error: Option -S cannot be used with -F" >&2
				return 1
			else
				STATCHANGE_FLAG=1
				STATCHANGE_VALUE=${OPTARG}
			fi
			;;
		?)   # unkown option
			return 1
			;;
		esac
	done

	if [ $? != 0 ]
	then
		return 1
	fi

	if [ ${NUM_ARGUMENTS} -ge ${OPTIND} ]
	then
		shift `expr $OPTIND - 1`
		if [ "X${DATABASE_FLAG}" != "X" -o "X${TABLE_FLAG}" != "X" ]
		then
			printf "${PROGNAME}: Syntax error - Options -d and -t cannot be used with database/table simple syntax\n" >&2
			return 1
		else
			for OPTION in $*
			do
				if [ "X"$DATABASE_FLAG != "X1" ]	
				then
					DATABASE_FLAG=1
					DATABASE=$OPTION
					shift
					continue	
				fi
				if [ "X"$TABLE_FLAG != "X1" ]	
				then
					TABLE_FLAG=1
					tabname=$OPTION
					shift
					continue
				fi
				echo "${PROGNAME}: Syntax error: ${OPTION}" >&2
				return 1
			done
                fi
        fi
	return 0
}






#--------------------------------------------------------
# script start...
#--------------------------------------------------------

NUM_ARGUMENTS=$#
get_args $*
if [ $? != 0 ]
then
	echo "Error parsing parameters" >&2
	show_help >&2
	exit 1
fi

until [ ${DATABASE} ]
do
  echo -n "What is the database name?: "
  read DATABASE
done
 
until [ ${tabname} ]
do
  echo -n "What is the table name?: "
  read tabname
done
 
#--------------------------------------------------------
# Check parameter values...
#--------------------------------------------------------
if [ "X${PRIORITY_FLAG}" = "X1" ]
then
	if [ 1 -gt ${priority}  -o  ${priority} -gt 100 ]
	then
		echo "Error: PDQPRIORITY must be between 0 and 100" >&2
		exit 1
	fi
fi

if [ "X${RESOLUTION_MEDIUM_FLAG}" = "X1" ]
then
	echo ${resolution_medium} | grep '^[0-9]\{0,3\}\.\{0,1\}[0-9]\{1,\}$' 2>&1 >/dev/null
	RESULT=$?
	if [ ${RESULT} != 0 -o ${resolution_medium} -gt 100 ]
	then
		echo "Error: RESOLUTION MEDIUM value must be numeric and less than or equal to 100" >&2
		exit 1
	fi
fi
 
if [ "X${RESOLUTION_HIGH_FLAG}" = "X1" ]
then
	echo ${resolution_high} | grep '^[0-9]\{0,3\}\.\{0,1\}[0-9]\{1,\}$' 2>&1 >/dev/null
	RESULT=$?
	if [ ${RESULT} != 0 -o ${resolution_high} -gt 100 ]
	then
		echo "Error: RESOLUTION HIGH value must be numeric and less than or equal to 100" >&2
		exit 1
	fi
fi

if [ "X${CONFIDENCE_FLAG}" = "X1" ]
then
	echo ${confidence} | grep "0\.[89][0-9]*" 2>&1 >/dev/null
	RESULT=$?
	if [ ${RESULT} != 0 ]
	then
		echo "Error: CONFIDENCE must be between 0.80 and 0.99" >&2
		exit 1
	fi
fi

if [ "X${STATCHANGE_FLAG}" = "X1" ]
then
	echo ${STATCHANGE_VALUE} | grep '^[0-9]\{1,3\}$' 2>&1 >/dev/null
	RESULT=$?
	if [ ${RESULT} != 0 -o ${STATCHANGE_VALUE} -lt 1 -o ${STATCHANGE_VALUE} -gt 100 ]
	then
		echo "${PROGNAME} Syntax error: STATCHANGE value must be numeric and between 1 and 100" >&2
		exit 1
	fi
fi

#--------------------------------------------------------
# define filenames using process id
#--------------------------------------------------------
SQL_FILE=/tmp/${PROGNAME}$$.sql
IDX_HEADER_COLUMNS_FILE=/tmp/${PROGNAME}_$$.idx_header
NONINDEX_HEADER_COLUMNS_FILE=/tmp/${PROGNAME}_$$.non_idxhdr
INDEXED_COLUMNS_FILE=/tmp/${PROGNAME}_$$.idx
NON_INDEXED_COLUMNS_FILE=/tmp/${PROGNAME}_$$.non_indexed
SQL_ERROR_FILE=/tmp/${PROGNAME}_$$.sqlerror
SQL_OUTPUT_FILE=/tmp/${PROGNAME}_$$.sqlout

#--------------------------------------------------------
# setup function for cleaning up on exit
#--------------------------------------------------------
clean_up()
{
	rm -f ${SQL_FILE} ${IDX_HEADER_COLUMNS_FILE} ${INDEXED_COLUMNS_FILE} ${NONINDEX_HEADER_COLUMNS_FILE} ${SQL_ERROR_FILE} ${SQL_OUTPUT_FILE} ${NON_INDEXED_COLUMNS_FILE}
}
trap clean_up 0
 
if [ "X"${ANSI_USER_FLAG} = "X1" ]
then
	ANSI_CLAUSE="and t.owner = '${ANSI_USER}'"
else
	ANSI_CLAUSE=""
fi

if [ "X${DIRTY_READ_FLAG}" = "X1" ]
then
	ISOLATION_CLAUSE="SET ISOLATION TO DIRTY READ;"
else
	ISOLATION_CLAUSE=""
fi

if [ "X${LOCK_MODE_FLAG}" = "X1" ]
then
	LOCK_MODE_CLAUSE="SET LOCK MODE TO WAIT ${LOCK_MODE_TIME};"
else
	LOCK_MODE_CLAUSE=""
fi

#--------------------------------------------------------
# get the aux column files...
#--------------------------------------------------------
dbaccess ${DATABASE} 1>/dev/null 2>${SQL_ERROR_FILE} <<EOSQL
-------------------------------------------------------
-- find the index header columns
-------------------------------------------------------
$ISOLATION_CLAUSE
$LOCK_MODE_CLAUSE
unload to ${IDX_HEADER_COLUMNS_FILE} delimiter ' '
select unique trim(colname)
from informix.systables t, informix.sysindexes i, informix.syscolumns c
where tabname = '${tabname}' 
and t.tabid = i.tabid
and t.tabid = c.tabid
and colno = abs(part1)
$ANSI_CLAUSE
order by 1;

--------------------------------------------------------
-- find all the non index header columns
--------------------------------------------------------
unload to ${NONINDEX_HEADER_COLUMNS_FILE} delimiter ' '
select unique trim(colname)
from informix.syscolumns c, informix.systables t
where c.tabid = t.tabid
and t.tabname = '${tabname}'
and c.colno not in ( select abs(i.part1) from informix.sysindexes i where i.tabid = t.tabid)
$ANSI_CLAUSE
order by 1;

--------------------------------------------------------
-- find the indexed columns
--------------------------------------------------------
select i.part1  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part2  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part3  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part4  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part5  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part6  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part7  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part8  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part9  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part10 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part11 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part12 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part13 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part14 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part15 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
select i.part16 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid
into temp t_aux;

unload to ${INDEXED_COLUMNS_FILE} delimiter ' '
select unique trim(colname)
from informix.syscolumns c, informix.systables t
where c.tabid = t.tabid
and t.tabname = '${tabname}'
$ANSI_CLAUSE
and c.colno in (select abs(part_x)  from t_aux)
order by 1;

--------------------------------------------------------
-- find the non indexed columns
--------------------------------------------------------
unload to ${NON_INDEXED_COLUMNS_FILE} delimiter ' '
select unique trim(colname)
from informix.syscolumns c, informix.systables t
where c.tabid = t.tabid
and t.tabname = '${tabname}'
$ANSI_CLAUSE
and c.colno not in (select abs(part_x) from t_aux)
order by 1;
EOSQL

if [ $? != 0 ]
then
	printf "${PROGNAME} Error: dbaccess error when fetching column information for table ${DATABASE}@${INFORMIXSERVER}:${tabname}\n">&2
	cat ${SQL_ERROR_FILE} >&2
	exit 1
fi

#--------------------------------------------------------
# start the SQL script preparation
#--------------------------------------------------------
echo ""> ${SQL_FILE}
OUTPUT_PREFIX=""
#OUTPUT_PREFIX="${DATABASE}@${INFORMIXSERVER}:"
printf "\n-- Update statistics for table ${DATABASE}@${INFORMIXSERVER}:${tabname}\n-- Generated by ${PROGNAME} ${VERSION} on `date` \n\n" >>${SQL_FILE}

if [ "X${DIRTY_READ_FLAG}" = "X1" ]
then
	
	printf "\n-- SET ISOLATION CLAUSE\n${ISOLATION_CLAUSE}\n" >> ${SQL_FILE}
fi

if [ "X${LOCK_MODE_FLAG}" = "X1" ]
then
	printf "\n-- SET LOCK MODE CLAUSE\n${LOCK_MODE_CLAUSE}\n" >> ${SQL_FILE}
fi


if [ "X${STATCHANGE_FLAG}" = "X1" ]
then
	printf "\n-- SET STATCHANGE ENVIRONMENT\nSET ENVIRONMENT STATCHANGE '${STATCHANGE_VALUE}';\n" >> ${SQL_FILE}
fi

if [ "X${ANSI_USER_FLAG}" = "X1" ]
then
	tabowner="\"$ANSI_USER\"."
else
	tabowner=""
fi
if [ "X${TIMINGS_FLAG}" = "X1" ]
then
	printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabowner}${tabname} S: '||current year to fraction(3) from informix.systables where tabid = 1;\n" >>${SQL_FILE}
fi

if [ "X${EXPLAIN_FLAG}" = "X1" ]
then
	printf "\n-- Obtain statistics\nset explain on;\n" >>${SQL_FILE}
else
	if [ "X${EXPLAIN_FLAG}" = "X2" ]
	then
		printf "\n-- Obtain statistics\nset explain file to '${explain_file}';\n" >>${SQL_FILE}
	fi
fi
if [ "X"${PRIORITY_FLAG} = "X1" ]
then
	printf "\n-- Set PDQPRIORITY\nset pdqpriority ${priority};\n" >>${SQL_FILE}
fi


if [ "X${FORCE_FLAG}" = "X1" ]
then
	FORCE_CLAUSE=" FORCE "
else
	FORCE_CLAUSE=""
fi

#-------------------------------------------------------
# Create sql statements for medium distributions 
#-------------------------------------------------------

LINE_COUNT=`wc -l ${NONINDEX_HEADER_COLUMNS_FILE} | awk '{print $1}'`

if [ "X${LINE_COUNT}" != "X0" ]
then
	if [ "X${RESOLUTION_MEDIUM_FLAG}" = "X1" -o "X${CONFIDENCE_FLAG}" = "X1" -o "X${SAMPLING_SIZE}" = "X1" ]
	then
		if [ "X${SAMPLING_FLAG}" = "X1" ]
		then
			sampling_clause=" sampling size ${sampling} "
		else
			sampling_clause=""
		fi

		if [ "X${RESOLUTION_MEDIUM_FLAG}" != "X1" ]
		then
			resolution_clause_medium=" resolution ${DEFAULT_RESOLUTION_MEDIUM} ${confidence} "
		else
			resolution_clause_medium=" resolution ${resolution_medium} ${confidence} "
		fi
	fi
	if [ "X${TIMINGS_FLAG}" = "X1" ]
	then
		printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabowner}${tabname} M: '||current year to fraction(3) from informix.systables where tabid = 1;\n" >>${SQL_FILE}
	fi

	printf "\n-- MEDIUM distributions only for all columns that are not head of any index\nupdate statistics medium for table ${tabowner}\"${tabname}\"\n    (" >>${SQL_FILE}
	FIRST=1
	while read COLNAME
	do
		if [ $FIRST = 1 ]
		then
			printf "%s" ${COLNAME} >> ${SQL_FILE}
			FIRST=0
		else
			printf ",%s" ${COLNAME} >>${SQL_FILE}
		fi
	done < ${NONINDEX_HEADER_COLUMNS_FILE}
	printf  ")\n${sampling_clause}${resolution_clause_medium} distributions only${FORCE_CLAUSE};\n" >>${SQL_FILE}
fi
if [ "X${ANSI_FLAG}" = "X1" ]
then
	printf "\nCOMMIT;\n" >>${SQL_FILE}
fi
 
#-------------------------------------------------------
# Create sql statements for high distributions
#-------------------------------------------------------

LINE_COUNT=`wc -l ${IDX_HEADER_COLUMNS_FILE} | awk '{print $1}'`
if [ "X${LINE_COUNT}" != "X0" ]
then
	if [ "X${RESOLUTION_HIGH_FLAG}" = "X1" ]
	then
		resolution_clause_high=" resolution ${resolution_high} "
	fi
	if [ "X${TIMINGS_FLAG}" = "X1" ]
	then
		printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabowner}${tabname} H: '||current year to fraction(3) from informix.systables where tabid = 1;\n" >>${SQL_FILE}
	fi

	printf  "\n-- HIGH distributions only for all columns that are head of any index\nupdate statistics high for table ${tabowner}\"${tabname}\"\n    (" >>${SQL_FILE}
	FIRST=1
	while read COLNAME
	do
		if [ $FIRST = 1 ]
		then
			printf "%s" ${COLNAME} >> ${SQL_FILE}
			FIRST=0
		else
			printf ",%s" ${COLNAME} >>${SQL_FILE}
		fi
	done <${IDX_HEADER_COLUMNS_FILE}
	printf ")\n${resolution_clause_high} distributions only${FORCE_CLAUSE};\n" >>${SQL_FILE}
fi
if [ "X${ANSI_FLAG}" = "X1" ]
then
	printf "\nCOMMIT;\n" >>${SQL_FILE}
fi

 
#-------------------------------------------------------
# Create sql statements for low 
#-------------------------------------------------------
if [ "X${TIMINGS_FLAG}" = "X1" ]
then
	printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabowner}${tabname} L: '||current year to fraction(3) from informix.systables where tabid = 1;\n" >>${SQL_FILE}
fi

case "X${LOW_MODE_FLAG}" in
X)
	LINE_COUNT=`wc -l ${INDEXED_COLUMNS_FILE} | awk '{print $1}'`
	if [ "X${LINE_COUNT}" != "X0" ]
	then
		printf  "\n-- LOW for all columns beloging to any index\nupdate statistics low for table ${tabowner}\"${tabname}\"\n    (" >>${SQL_FILE}
		FIRST=1
		while read COLNAME
		do
			if [ $FIRST = 1 ]
			then
				printf "%s" ${COLNAME} >> ${SQL_FILE}
				FIRST=0
			else
				printf ",%s" ${COLNAME} >>${SQL_FILE}
			fi
		done <${INDEXED_COLUMNS_FILE}
		printf ")${FORCE_CLAUSE};\n\n" >>${SQL_FILE}
	else
		printf "\n-- LOW for table if table has no indexes\nupdate statistics low for table ${tabowner}\"${tabname}\"${FORCE_CLAUSE};\n\n" >>${SQL_FILE}
	fi
	;;
X1)
	LINE_COUNT=`wc -l ${NON_INDEXED_COLUMNS_FILE} | awk '{print $1}'`
	if [ "X${LINE_COUNT}" != "X0" ]
	then
		printf  "\n-- Using LOW quick mode... LOW for all columns NOT beloging to any index\nupdate statistics low for table ${tabowner}\"${tabname}\"\n    (" >>${SQL_FILE}
		FIRST=1
		while read COLNAME
		do
			if [ $FIRST = 1 ]
			then
				printf "%s" ${COLNAME} >> ${SQL_FILE}
				FIRST=0
			else
				printf ",%s" ${COLNAME} >>${SQL_FILE}
			fi
		done <${NON_INDEXED_COLUMNS_FILE}
		printf ")${FORCE_CLAUSE};\n\n" >>${SQL_FILE}
	else
		COLNAME=`head -1 ${INDEXED_COLUMNS_FILE}`
		printf "\n-- Using LOW quick mode, but all columns are indexed! Using just one column...\nupdate statistics low for table${tabowner} \"${tabname}\"( ${COLNAME} )${FORCE_CLAUSE};\n\n" >>${SQL_FILE}
	fi
	;;
esac

if [ "X${ANSI_FLAG}" = "X1" ]
then
	printf "\nCOMMIT;\n" >>${SQL_FILE}
fi

if [ "X${TIMINGS_FLAG}" = "X1" ]
then
printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabowner}${tabname} E: '||current year to fraction(3) from informix.systables where tabid = 1;\n" >>${SQL_FILE}
fi


#-------------------------------------------------------
# Execute SQL instructions
#-------------------------------------------------------
case X${DISPLAY_FLAG} in
X1)
	cat ${SQL_FILE}
	;;
X2)
	cat ${SQL_FILE}
	dbaccess ${DATABASE} - <${SQL_FILE} 2>${SQL_ERROR_FILE}
	if [ $? != 0 ]
	then
		printf "${PROGNAME} Error: dbaccess error when executing SQL with update statistics statements: ${tabname}@${DATABASE}\n">&2
		cat ${SQL_ERROR_FILE} >&2
		exit 1
	fi
	;;
X*)
	dbaccess ${DATABASE} - <${SQL_FILE} 2>${SQL_ERROR_FILE}
	if [ $? != 0 ]
	then
		printf "${PROGNAME} Error: dbaccess error when executing SQL with update statistics statements: ${tabname}@${DATABASE}\n">&2
		cat ${SQL_ERROR_FILE} >&2
		exit 1
	fi
	;;
esac
