#!/bin/ksh
# Copyright (c) 2010-2016 Fernando Nunes - domusonline@gmail.com
# License: This script is licensed as GPL V2 ( http://www.gnu.org/licenses/old-licenses/gpl-2.0.html )
# $Author: Fernando Nunes - domusonline@gmail.com $
# $Revision 2.0.1 $
# $Date 2016-02-22 02:38:48$
# Disclaimer: This software is provided AS IS, without any kind of guarantee. Use at your own risk.
#             Although the author is/was an IBM employee, this software was created outside his job engagements.
#             As such, all credits are due to the author.

show_help()
{
        echo "${PROGNAME}: -V | -h |  -l lock_limit [ -u <user_list> ] [ -k | -r ] [ -f <log_file> ] [ -c <class_id> ] [ -s <severity> ] [-m <class_msg> ]" >&1
        echo "               -V shows script version" >&1
        echo "               -h shows this help" >&1
        echo "               -l <lock_limit> Maximum number of locks accepted" >&1
        echo "               -u <user_list> list of users for exceptions (comma separated)" >&1
	echo "               -k Force the kill of the sessions" >&1
	echo "               -r Just report the offending sessions" >&1
	echo "               -f <log_file> use log_file for recording the script activity" >&1
	echo "               -c <class_id> use class_id as the class number for alarmprogram" >&1
	echo "               -s <severity> use severity as the severity for alarmprogram" >&1
	echo "               -m <message> use message as the class message for alarmprogram" >&1
        echo "Ex: ${PROGNAME} -l 50000 -u informix,johndoe" >&1
}

PROGNAME=`basename $0`
VERSION=`echo "$Revision 2.0.1 $" | cut -f2 -d' '`
LOG_FILE=/usr/informix/etc/${PROGNAME}.${INFORMIXSERVER}.log

arg_ok='Vhl:u:rkf:c:s:m:'
while getopts ${arg_ok} FLAG
do
        case $FLAG in
        h)   # show help
                show_help
                exit 0
                ;;
        V)   # show version
                echo "${PROGNAME} ${VERSION}" >&1
                exit 0
                ;;
        l)   # Limit locks
		LIMIT_LOCK_FLAG=1
                LIMIT_LOCK_NUMBER="$OPTARG"
                echo ${LIMIT_LOCK_NUMBER} | grep "^[0-9][0-9]*$" >/dev/null
                if [ $? != 0 ]
                then
                        printf "${PROGNAME}: Lock Limit for -l option has to be numeric\n" >&2
                        exit 1
                fi
                ;;
        u)   # USER_EXCEPTION
                USER_EXCEPTION_FLAG=1
                USER_EXCEPTION_LIST="${OPTARG}"
                echo ${USER_EXCEPTION_LIST} | egrep "^[a-z_][a-z0-9]*(,[a-z][a-z0-9]*)*$" >/dev/null
                if [ $? != 0 ]
                then
                        printf "${PROGNAME}: User list must be a comma separated list of valid usernames\n" >&2
                        exit 1
                fi
                ;;
	k)
		# KILL SESSION
		KILL_FLAG=1
		if [ "X${REPORT_FLAG}" = "X1" ]
		then
			printf "${PROGNAME}: Kill flag and report flag are mutually exclusive\n" >&2
			exit 1
		fi
		;;
	r)
		# Report Only
		REPORT_FLAG=1
		if [ "X${KILL_FLAG}" = "X1" ]
		then
			printf "${PROGNAME}: Report flag and kill flag are mutually exclusive\n" >&2
			exit 1
		fi
		;;
	f)
		# Log file
		LOG_FILE="${OPTARG}"
		;;
	c)
		# Alarm Class ID
		EXPR_ALARM_CLASS_ID_FLAG=1
		EXPR_ALARM_CLASS_ID=${OPTARG}
		;;
	s)
		# Alarm severity
		EXPR_ALARM_SEVERITY_FLAG=1
		EXPR_ALARM_SEVERITY=${OPTARG}
		case ${EXPR_ALARM_SEVERITY} in
		1|2|3|4|5)
			#ok...
			;;
		*)
			#not ok
			printf "${PROGNAME}: Severity must be a number between 1 and 5\n" >&2
			exit 1
		esac
		;;
	m)
		# Alarm Message
		EXPR_ALARM_MESSAGE_FLAG=1
		EXPR_ALARM_MESSAGE="${OPTARG}"
		;;
        :|?)   # Invalid argument
                printf "${PROGNAME}: Invalid argument given! $FLAG | $OPTIND | $OPTARG\n">&2
                show_help
                ;;
        esac
done


if [ "X${LIMIT_LOCK_FLAG}" != "X1" ]
then
	printf "${PROGNAME} lock limit flag is required\n" >&2
	exit 1	
fi

if [ "X${KILL_FLAG}" != "X1" -a "X${REPORT_FLAG}" != "X1" ]
then
	printf "${PROGNAME} Kill or report flag must be specified\n" >&2
	exit 1
fi


if [ "X${USER_EXCEPTION_FLAG}" = "X0" ]
then
	USER_EXCEPTION_LIST=`echo "${USER_EXCEPTION_LIST} " | sed 's/,/ /'`
fi

if [ -d "${LOG_FILE}" ]
then
	echo "Log file ${LOG_FILE} option must point to a file, not a directory" >&2
	exit 1
else
	if [ -f "${LOG_FILE}" ]
	then
		if [ ! -w "${LOG_FILE}" ]
		then
			echo "Log file ${LOG_FILE} must have write permissions" >&2
			exit 1
		fi
	else
		LOG_FILE_DIR=`dirname ${LOG_FILE}`
		if [ ! -d "${LOG_FILE_DIR}" ]
		then
			echo "Log file ${LOG_FILE} points to a non-existent directory, or no access permissions" >&2
			exit 1
		else
			if [ ! -w "${LOG_FILE_DIR}" ]
			then
				echo "Log file directory "${LOG_FILE_DIR}" has no write permissions" >&2
				exit 1
			fi
		fi
	fi
fi

if [ "X${EXPR_ALARM_CLASS_ID_FLAG}" != "X1" ]
then
	EXPR_ALARM_CLASS_ID=910
fi
if [ "X${EXPR_ALARM_SEVERITY_FLAG}" != "X1" ]
then
	EXPR_ALARM_SEVERITY=3
fi
if [ "X${ALARM_MESSAGE_FLAG}" != "X1" ]
then
	EXPR_ALARM_MESSAGE="Too many locks"
fi

which ixses | grep "^no ixses" >/dev/null 2>/dev/null
if [ $? = 0 ]
then
	SESSION_COMMAND="onstat -g ses"
else
	SESSION_COMMAND="ixses"
fi


KILL_COMMAND="onmode -z "
HEADER=0
PREV_SESSION=0
MYDATE=`date +"%Y%m%d %H:%M:%S"`
onstat -u | awk -v LIMIT_LOCK_NUMBER="$LIMIT_LOCK_NUMBER" '{if ( int($8) > LIMIT_LOCK_NUMBER ) { print $3 " " $4 " " $8}}' | sort -nk 1 | while read MYSESSION MYUSER MYNLOCKS
do
	if [ $MYSESSION = $PREV_SESSION ]
	then
		continue
	else
		PREV_SESSION=$MYSESSION
	fi

	if [ "X${HEADER}" = "X0" ]
	then
		HEADER=1
		printf "#-- START CYCLE ${MYDATE} -- Sessions with nr of locks > %-10s --------------------------------\n\n" $LIMIT_LOCK_NUMBER >>${LOG_FILE}
	fi

	ALARM_SCRIPT=`grep -v "^[ 	]*#" $INFORMIXDIR/etc/$ONCONFIG | grep "^[ 	]*ALARMPROGRAM[ 	]" | awk '{print $2}'| cut -f1 -d'#'`



	printf "\n#- START SESSION: $MYSESSION $MYUSER ( $MYNLOCKS )\n" >>${LOG_FILE}
	$SESSION_COMMAND $MYSESSION >>${LOG_FILE}

	KILLED=n
	if [ "X${KILL_FLAG}" = "X1" ]
	then
		echo "$USER_EXCEPTION_LIST " | grep "${MYUSER} " > /dev/null
		if [ $? != 0 ]
		then
			printf "#-- Killing session %-10s --------------------------------------------------------------------------------\n" $MYSESSION >>${LOG_FILE}
			${KILL_COMMAND} $MYSESSION
			KILLED=y
		fi
	fi

	if [ "X${KILLED}" = "Xy" ]
	then
		EXPR_ALARM_SEND="Session $MYSESSION from user $MYUSER had more locks than the max defined: $MYNLOCKS/$LIMIT_LOCK_NUMBER :Killed!"
	else
		EXPR_ALARM_SEND="Session $MYSESSION from user $MYUSER has more locks than the max defined: $MYNLOCKS/$LIMIT_LOCK_NUMBER"
	fi

	${ALARM_SCRIPT} ${EXPR_ALARM_SEVERITY} ${EXPR_ALARM_CLASS_ID} "${EXPR_ALARM_MESSAGE}" "${EXPR_ALARM_SEND}"
done


MYDATE=`date +"%Y%m%d %H:%M:%S"`
if [ "X${HEADER}" = "X1" ]
then
	printf "#-- END CYCLE ${MYDATE} -------------------------------------------------------------------------------\n">>${LOG_FILE}
fi
