#!/bin/sh
# Name: $RCSfile$
# CVS file: $Source$
# CVS id: $Header$
# Revision: $Revision$
# Revised on: $Date$
# Revised by: $Author$
# Support: Fernando Nunes - domusonline@domus.online.pt
# Licence: This script is licenced as GPL ( http://www.gnu.org/licenses/gpl.html )
# History:

usage()
{
	echo "$PROGNAME Usage:" >&2
	echo "$PROGNAME <existing INFORMIXDIR> <new virt INFORMIXDIR> <version>" >&2
}



PROGNAME=`basename $0`
VERSION=1.2

case $# in
3)
	EXISTING_IXDIR=$1
	NEW_IXDIR=$2
	IX_VERSION=$3
	case $IX_VERSION in
	7)
		IX_SUB_DIRS="aaodir bin dbssodir demo etc forms gls help incl ism lib msg release snmp"
		IX_DIRS="bin demo forms gls help incl ism lib msg release snmp"
		;;
	9)
		IX_SUB_DIRS="aaodir bin dbssodir demo doc etc extend forms gls help incl ism lib msg release snmp"
		IX_DIRS="bin demo doc extend forms gls help incl ism lib msg release snmp"
		;;
	10)
		IX_SUB_DIRS="aaodir bin dbssodir demo doc etc extend forms gls help incl ism lib msg release snmp ids_license master_license"
		IX_DIRS="bin demo doc extend forms gls help incl ism lib msg release snmp ids_license master_license"
		;;
	*)
		echo "Version can only be 7, 9 or 10" >&2
		usage
		exit 1
		;;
	esac
	;;
*)
	usage
	exit 1
esac

SO=`uname -s | tr "[A-Z]" "[a-z]"`
case $SO in
sunos*|osf*)
        AWK=nawk
        ;;
linux|*)
        AWK=awk
        ;;
esac

export AWK

MY_USER=`id | ${AWK} -F"[()]" ' { print $2 } '`

case $MY_USER in
informix|root)
        ;;
*)
        echo "This utility must be run as root or informix" >&2
        exit 1
        ;;
esac


if [ ! -d $EXISTING_IXDIR ]
then
	echo "$EXISTING_IXDIR is not an existing dir!" >&2
	exit 1
else
	CURR_DIR=`pwd`
	cd $EXISTING_IXDIR
	EXISTING_IXDIR=`pwd`
	cd $CURR_DIR
fi


for dir in $IX_SUB_DIRS
do
	if [ ! -d $EXISTING_IXDIR/$dir ]
	then
		echo "$EXISTING_IXDIR/$dir does not exist!... Aborting..." >&2
#		exit 1	
	fi
done


if [ ! -w $NEW_IXDIR ]
then
	mkdir $NEW_IXDIR
	if  [ $? != 0 ]
	then
		echo "Error creating non existing new INFORMIXDIR: $NEW_IXDIR" >&2
		exit 1
	fi
	if [ $MY_USER != "informix" ]
	then
		chown informix:informix $NEW_IXDIR
	fi
	chmod 755 $NEW_IXDIR
fi

cd $NEW_IXDIR
NEW_IXDIR=`pwd`
cd $NEW_IXDIR

for dir in $IX_DIRS
do
	if [ $MY_USER != "informix" ]
	then
		su informix -c "ln -s $EXISTING_IXDIR/$dir ."
	else
		ln -s $EXISTING_IXDIR/$dir .
	fi
done

mkdir dbssodir aaodir etc
cp -pR $EXISTING_IXDIR/etc/* $NEW_IXDIR/etc
cp -pR $EXISTING_IXDIR/dbssodir/* $NEW_IXDIR/dbssodir
cp -pR $EXISTING_IXDIR/aaodir/* $NEW_IXDIR/aaodir

if [ $MY_USER != "informix" ]
then
	#Future versions should handle role separation
	chown informix:informix $NEW_IXDIR/dbssodir
	chown informix:informix $NEW_IXDIR/etc
	chown informix:informix $NEW_IXDIR/aaodir
fi
chmod 770 dbssodir aaodir
chmod 755 etc
